export const PURCHASE_ORDER_STATUS = {
  PENDING: "PENDING",
  RECEIVED: "RECEIVED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};
export const SALES_ORDER_STATUS = {
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

export const ORDER_TYPE = {
  SALES: "SALES",
  PURCHASE: "PURCHASE",
};

export const INVENTORY_TRANSACTION_TYPE = {
  PURCHASE: "PURCHASE",
  SALE: "SALE",
  ADJUSTMENT: "ADJUSTMENT",
  RETURN: "RETURN",
  TRANSFER: "TRANSFER",
  OTHER: "OTHER",
  EXPIRY: "EXPIRY",
  CANCELLATION: "CANCELLATION",
};

export const PAGINATION = {
  LIMIT: 25,
  PAGE: 1,
};

// PENDING
// RECEIVED
// COMPLETED
