export const PURCHASE_ORDER_STATUS = {
  PENDING: "PENDING",
  RECEIVED: "RECEIVED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};
export const SALES_ORDER_STATUS = {
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

export const ORDER_TYPE = {
  SALES: "SALES",
  PURCHASE: "PURCHASE",
};

export const INVENTORY_TRANSACTION_TYPE = {
  PURCHASE: "PURCHASE",
  SALE: "SALE",
  PRICE_ADJUSTMENT: "PRICE_ADJUSTMENT",
  RETURN: "RETURN",
  CANCELLATION: "CANCELLATION",
  BREAK_PACK: "BREAK_PACK",
  REPACK: "REPACK",
};

export const PAGINATION = {
  LIMIT: 25,
  PAGE: 1,
};

export const MODE_OF_PAYMENT = {
  CASH: "CASH",
  CHECK: "CHECK",
};

export const UNIT = {
  BOX: "BOX",
  BAG: "BAG",
  GAL: "GAL",
  PACK: "PACK",
  SET: "SET",
  PCS: "PCS",
};

// PENDING
// RECEIVED
// COMPLETED
