export const ORDER_STATUS = {
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

export const INVENTORY_TRANSACTION_TYPE = {
  PURCHASE: "PURCHASE",
  SALE: "SALE",
  ADJUSTMENT: "ADJUSTMENT",
  RETURN: "RETURN",
  TRANSFER: "TRANSFER",
  OTHER: "OTHER",
  EXPIRY: "EXPIRY",
  CANCELLATION: "CANCELLATION",
};
