/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface category {
  description?: string;
  name: string;
}

export interface customer {
  address: string;
  contact?: string | null;
  email?: string | null;
  isActive?: boolean;
  name: string;
  notes?: string;
  phone: string;
}

export interface inventory {
  id?: number;
  productId: number;
  quantity: number;
}

export interface inventoryPriceAdjustment {
  price: number;
}

export interface inventoryTransaction {
  inventoryId: number;
  newValue: number;
  orderId?: number;
  orderType?: string;
  previousValue: number;
  transactionType: string;
  value: number;
}

export interface login {
  password: string;
  username: string;
}

export interface product {
  categoryId: number;
  combinations?: productCombinations[];
  description?: string | null;
  name: string;
  unit: string;
  variants?: variant[];
}

export interface productCombinations {
  id?: number;
  price: number;
  productId?: number;
  reorderLevel: number;
  sku: string;
  values?: variantValue[];
}

export interface purchaseOrder {
  checkNumber?: string | null;
  deliveryDate: Date;
  dueDate?: Date;
  internalNotes?: string | null | '';
  modeOfPayment: string;
  notes?: string | null | '';
  orderDate: Date;
  purchaseOrderItems: purchaseOrderItem[];
  purchaseOrderNumber: string;
  receivedDate?: Date;
  supplierId: number;
}

export interface purchaseOrderChangeStatus {
  status?: 'VOID';
}

export interface purchaseOrderItem {
  cancellationReason?: string | null;
  combinationId: number;
  discount?: number | null;
  discountNote?: string | null | '';
  id?: number;
  originalPrice?: number | null;
  quantity: number;
  status?: 'PENDING' | 'RECEIVED' | 'COMPLETED' | 'CANCELLED';
  unitPrice: number;
}

export interface purchaseOrderStatus {
  cancellationReason?: string | null;
  status?: 'PENDING' | 'RECEIVED' | 'COMPLETED' | 'CANCELLED';
}

export interface purchaseOrderUpdate {
  checkNumber?: string | null;
  deliveryDate: Date;
  dueDate?: Date;
  internalNotes?: string | null;
  modeOfPayment: string;
  notes?: string | null;
  purchaseOrderItems: purchaseOrderItem[];
  purchaseOrderNumber: string;
  supplierId: number;
}

export interface repackInventory {
  categoryId: number;
  description?: string | null;
  name: string;
  parentId: number;
  price: number;
  pullOutQuantity: number;
  repackQuantity: number;
  unit: string;
}

export interface salesOrder {
  customer: string;
  deliveryDate: Date;
  notes?: string | null;
  orderDate: Date;
  receivedDate?: Date;
  salesOrderItems: salesOrderItem[];
}

export interface salesOrderItem {
  discount?: number | null;
  inventory?: object;
  inventoryId: number;
  originalPrice?: number | null;
  quantity: number;
  status?: 'PENDING' | 'COMPLETED' | 'CANCELLED';
  unitPrice: number;
}

export interface salesOrderStatus {
  status?: 'PENDING' | 'COMPLETED' | 'CANCELLED';
}

export interface supplier {
  address: string;
  contact?: string | null;
  email?: string | null;
  isActive?: boolean;
  name: string;
  notes?: string;
  phone: string;
}

export interface userBase {
  confirmPassword: string;
  email: string;
  isActive?: boolean;
  name: string;
  password: string;
  username: string;
}

export interface userBase {
  email: string;
  isActive?: boolean;
  name: string;
}

export interface variant {
  id?: number;
  name: string;
  productId?: number;
  values: (variantValue | variantValuePayload)[];
}

export interface variantValue {
  id?: number;
  value: string;
  variantTypeId?: number;
}

export type variantValuePayload = string;
