const ORDER_STATUS = {
  DRAFT: "DRAFT",
  RECEIVED: "RECEIVED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  VOID: "VOID",
};

const ORDER_TYPE = {
  SALE: "SALE",
  PURCHASE: "PURCHASE",
};

const INVENTORY_MOVEMENT_TYPE = {
  IN: "IN",
  OUT: "OUT",
  ADJUSTMENT: "ADJUSTMENT",
  RETURN: "RETURN",
  CANCELLATION: "CANCELLATION",
  BREAK_PACK: "BREAK_PACK",
  RE_PACK: "RE_PACK",
};
const INVENTORY_MOVEMENT_REFERENCE_TYPE = {
  GOOD_RECEIPT: "GOOD_RECEIPT",
  SALES_ORDER: "SALES_ORDER",
  STOCK_ADJUSTMENT: "STOCK_ADJUSTMENT",
  BREAK_PACK: "BREAK_PACK",
};

const PAGINATION = {
  LIMIT: 25,
  PAGE: 1,
};

const MODE_OF_PAYMENT = {
  CASH: "CASH",
  CHECK: "CHECK",
  EWALLET: "EWALLET",
  BANK: "BANK",
};

const BASE_UNIT = {
  PCS: "PCS",
  KGS: "KGS",
  BTL: "BTL",
  RLS: "RLS",
  MTS: "MTS",
  FTS: "FTS",
  LTS: "LTS",
};
const UNIT = {
  BOX: "BOX",
  BAG: "BAG",
  GAL: "GAL",
  PCK: "PCK",
  SET: "SET",
  DOZ: "DOZ",
};

const STOCK_ADJUSTMENT_TYPE = {
  DAMAGED: "DAMAGED",
  LOST: "LOST",
  FOUND: "FOUND",
  EXPIRED: "EXPIRED",
  SAMPLE: "SAMPLE",
  ERROR_CORRECTION: "ERROR_CORRECTION",
  SUPPLIER_BONUS: "SUPPLIER_BONUS",
  RETURN_TO_STOCK: "RETURN_TO_STOCK",
  OTHER: "OTHER",
};

const INVOICE_STATUS = {
  DRAFT: "DRAFT",
  POSTED: "POSTED",
  PARTIALLY_PAID: "PARTIALLY_PAID",
  PAID: "PAID",
};
module.exports = {
  ORDER_STATUS,
  ORDER_TYPE,
  INVENTORY_MOVEMENT_TYPE,
  PAGINATION,
  MODE_OF_PAYMENT,
  BASE_UNIT,
  UNIT,
  STOCK_ADJUSTMENT_TYPE,
  INVOICE_STATUS,
  INVENTORY_MOVEMENT_REFERENCE_TYPE,
};
